### ISSUE TITLE
Not returning card data

### ISSUE THREAD

**Issue by AghaShayan123** [howljs/rn-card-scanner#15]
I have cloned an example app and run but it's not return data after scanning it's not going to the card details screen always remaining on scan screen when card is placed in a frame.
I am using Redmi note 8 Android version is 11

**Comment by thidasapankaja** [comment]
Same happening for me. Always coming `undefined` .
Did you found the solution

**Comment by AghaShayan123** [comment]
@thidasapankaja still not yet

**Comment by sjovicic** [comment]
I have the same issue.

On android logcat I get this:

`2024-06-26 13:25:44.310  1623-1623  RecognitionCore         pid-1623                             E  initialization failed
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libcardrecognizer.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1664)
                                                                                                    	at cards.pay.paycardsrecognizer.sdk.ndk.RecognitionCoreNdk.<clinit>(Unknown Source:7)
                                                                                                    	at cards.pay.paycardsrecognizer.sdk.ndk.RecognitionCoreNdk.l(Unknown Source:0)
                                                                                                    	at cards.pay.paycardsrecognizer.sdk.ndk.e.a(Unknown Source:15)
                                                                                                    	at cards.pay.paycardsrecognizer.sdk.ndk.e.c(Unknown Source:0)
                                                                                                    	at w1.k.<init>(Unknown Source:33)
                                                                                                    	at com.rncardscanner.h.<init>(Unknown Source:38)
                                                                                                    	at com.rncardscanner.CardScannerViewManager.createViewInstance(SourceFile:2)
                                                                                                    	at com.rncardscanner.CardScannerViewManager.createViewInstance(SourceFile:1)
                                                                                                    	at com.facebook.react.uimanager.ViewManager.createViewInstance(SourceFile:4)
                                                                                                    	at com.facebook.react.uimanager.ViewManager.createView(Unknown Source:0)
                                                                                                    	at com.facebook.react.uimanager.q.createView(Unknown Source:40)
                                                                                                    	at com.facebook.react.uimanager.g1$e.e(Unknown Source:23)
                                                                                                    	at com.facebook.react.uimanager.g1$a.run(Unknown Source:120)
                                                                                                    	at com.facebook.react.uimanager.g1.T(Unknown Source:53)
                                                                                                    	at com.facebook.react.uimanager.g1.w(Unknown Source:0)
                                                                                                    	at com.facebook.react.uimanager.g1$j.doFrameGuarded(Unknown Source:31)
                                                                                                    	at com.facebook.react.uimanager.f.doFrame(Unknown Source:0)
                                                                                                    	at com.facebook.react.modules.core.k$a.doFrame(Unknown Source:46)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:727)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

libary is linked from : node_modules/rn-card-scanner/android/src/main/java/cards/pay/paycardsrecognizer/sdk/ndk/RecognitionCoreNdk.java:37

**Comment by Osamasomy** [comment]
Scan not working!
